# Generated by Django 5.2.13 on 2026-04-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_game_genre_game_genres_game_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='rawd_id',
            new_name='rawg_id',
        ),
    ]
